/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package InterfazGrafica;

import LogicaNegocio.Negocio;
import LogicaNegocio.TipoEmpresa;
import LogicaNegocio.TipoRestaurante;
import LogicaNegocio.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CreacionNegocio extends javax.swing.JDialog {

    Usuario oUsuario = register.Registrado;
    TipoEmpresa tipo;
    TipoRestaurante Rest;

    /**
     * Creates new form CreacionNegocio
     */
    public CreacionNegocio(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        llenarNegocios();
        llenarRestaurantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblNombreNegocio = new javax.swing.JLabel();
        TxtNombreRest = new javax.swing.JTextField();
        LblTipoNegocio = new javax.swing.JLabel();
        CboEmpresa = new javax.swing.JComboBox<>();
        LblTipoRest = new javax.swing.JLabel();
        CboTipoRestaurante = new javax.swing.JComboBox<>();
        BtnConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        LblNombreNegocio.setForeground(new java.awt.Color(0, 57, 114));
        LblNombreNegocio.setText("Nombre del Negocio");

        LblTipoNegocio.setFont(LblTipoNegocio.getFont().deriveFont(LblTipoNegocio.getFont().getSize()+2f));
        LblTipoNegocio.setForeground(new java.awt.Color(0, 57, 114));
        LblTipoNegocio.setText("Tipo de Negocio");

        CboEmpresa.setFont(CboEmpresa.getFont().deriveFont(CboEmpresa.getFont().getSize()+2f));
        CboEmpresa.setForeground(new java.awt.Color(0, 57, 114));
        CboEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CboEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboEmpresaActionPerformed(evt);
            }
        });

        LblTipoRest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblTipoRest.setForeground(new java.awt.Color(0, 57, 114));
        LblTipoRest.setText("Tipo de Restaurante");

        CboTipoRestaurante.setFont(CboTipoRestaurante.getFont().deriveFont(CboTipoRestaurante.getFont().getSize()+2f));
        CboTipoRestaurante.setForeground(new java.awt.Color(0, 57, 114));
        CboTipoRestaurante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CboTipoRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboTipoRestauranteActionPerformed(evt);
            }
        });

        BtnConsulta.setForeground(new java.awt.Color(0, 0, 0));
        BtnConsulta.setText("Agregar Tienda");
        BtnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNombreRest, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNombreNegocio)
                    .addComponent(LblTipoNegocio)
                    .addComponent(CboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTipoRest)
                    .addComponent(CboTipoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConsulta))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblNombreNegocio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNombreRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblTipoNegocio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblTipoRest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CboTipoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnConsulta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboEmpresaActionPerformed
        if (CboEmpresa.getSelectedIndex() == 0) {
            LblTipoRest.setVisible(true);
            CboTipoRestaurante.setVisible(true);
        } else {
            LblTipoRest.setVisible(false);
            CboTipoRestaurante.setVisible(false);
        }
    }//GEN-LAST:event_CboEmpresaActionPerformed

    private void CboTipoRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboTipoRestauranteActionPerformed

    }//GEN-LAST:event_CboTipoRestauranteActionPerformed

    private void BtnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultaActionPerformed
        if (TxtNombreRest.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Indicar el nombre del restaurante");
            return;
        }
                switch (CboEmpresa.getSelectedIndex()) {
            case 0:
                tipo = TipoEmpresa.RESTAURANTE;
                break;
            case 1:
                tipo = TipoEmpresa.CAFETERIA;
                break;
            case 3:
                tipo = TipoEmpresa.EMPRESA;
                break;
            default:
                break;
        }
        switch (CboTipoRestaurante.getSelectedIndex()) {
            case 0:
                Rest = TipoRestaurante.COMIDARAPIDA;
                break;
            case 1:
                Rest = TipoRestaurante.ITALIANO;
                break;
            case 3:
                Rest = TipoRestaurante.ASIATICA;
                break;
            case 4:
                Rest = TipoRestaurante.MEXICANA;
                break;
            default:
                break;
        }
        if (Rest == null) {
            try {
                Negocio.agregarNegocio(new Negocio(tipo, oUsuario, TxtNombreRest.getText()));
            } catch (Exception ex) {
                Logger.getLogger(CreacionNegocio.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        } else if (Rest != null) {
            try {
                Negocio.agregarNegocio(new Negocio(tipo, oUsuario, TxtNombreRest.getText(), Rest));
            } catch (Exception ex) {
                Logger.getLogger(CreacionNegocio.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_BtnConsultaActionPerformed
    private void llenarRestaurantes() throws Exception {
        CboTipoRestaurante.removeAllItems();
        for (TipoRestaurante rest : TipoRestaurante.values()) {
            CboTipoRestaurante.addItem(rest.toString());
        }
    }

    private void llenarNegocios() throws Exception {
        CboEmpresa.removeAllItems();
        for (TipoEmpresa negocio : TipoEmpresa.values()) {
            CboEmpresa.addItem(negocio.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    CreacionNegocio dialog = new CreacionNegocio(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CreacionNegocio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsulta;
    private javax.swing.JComboBox<String> CboEmpresa;
    private javax.swing.JComboBox<String> CboTipoRestaurante;
    private javax.swing.JLabel LblNombreNegocio;
    private javax.swing.JLabel LblTipoNegocio;
    private javax.swing.JLabel LblTipoRest;
    private javax.swing.JTextField TxtNombreRest;
    // End of variables declaration//GEN-END:variables
}
